Pinterest/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from articleapp.views import ArticleListView

urlpatterns = [
    path('', ArticleListView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')),
    path('projects/', include('projectapp.urls')),
    path('subscribe/', include('subscribeapp.urls')),
    path('likes/', include('likeapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accountapp.views import AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = "accountapp"



urlpatterns = [
    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name = "login"),
    path('logout/', LogoutView.as_view(), name = "logout"),
    path('create/', AccountCreateView.as_view(), name='create'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),
]

articleapp/urls.py
from django.urls import path
from django.views.generic import TemplateView

from articleapp.views import ArticleCreateView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView, ArticleListView

app_name = 'articleapp'

urlpatterns=[
    path('list/', ArticleListView.as_view(), name = 'list'),
    path('create/', ArticleCreateView.as_view(), name = 'create'),
    path('detail/<int:pk>', ArticleDetailView.as_view(), name = 'detail'),
    path('update/<int:pk>', ArticleUpdateView.as_view(), name = 'update'),
    path('delete/<int:pk>', ArticleDeleteView.as_view(), name = 'delete'),

]

likeapp/urls.py
from django.urls import path

from likeapp.views import LikeArticleView

app_name ='likeapp'

urlpatterns = [
    path('article/like/<int:pk>', LikeArticleView.as_view(), name='article_like')
]

projectapp/urls.py
from django.urls import path

from projectapp.views import ProjectCreateView, ProjectDetailView, ProjectListView

app_name = 'projectapp'



urlpatterns = [
    path('create/', ProjectCreateView.as_view(), name = 'create'),
    path('detail/<int:pk>', ProjectDetailView.as_view(), name = 'detail'),
    path('list/', ProjectListView.as_view(), name = 'list')
]

subscribeapp/urls.py
from django.urls import path

from subscribeapp.views import SubscriptionView, SubscriptionListView

app_name= 'subscribeapp'

urlpatterns =[
    path('subscribe/', SubscriptionView.as_view(), name='subscribe'),
    path('list/', SubscriptionListView.as_view(), name='list')
]

templates/base.html
<!DOCTYPE html>
<html lang="ko">

{% include 'head.html' %}

<body style="font-family: 'NanumSquareRoundR';">
    {% include 'header.html' %}

    <hr>

    {% for message in messages %}
    <div class="text-center">
        {% if message.level == 40 %}
        <div class="btn btn-danger rounded-pill px-5 my-3">
            {{ message }}
        </div>
        {% else %}
        <div class="btn btn-success rounded-pill px-5 my-3">
            {{ message }}
        </div>
        {% endif %}
    </div>
    {% endfor %}
    {% block content %}
    {% endblock %}

    <hr>
    {% include 'footer.html' %}
</body>
</html>

templates/footer.html
<div style="text-align:center;">
    <div class="eliot_footer_button">
        <span>공지사항</span>
        <span>제휴문의</span>
        <span>서비스소개</span>
    </div>
    <div style="margin-top: 1rem;">
        <h6 class="eliot_footer_logo">Eliot Wokrs</h6>
    </div>
</div>

templates/head.html
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Pinterest</title>

<!-- BOOTSTRAP LINK  -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

<!-- Google Font/Gloria Hallelujah  -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Gloria+Hallelujah&display=swap" rel="stylesheet">

<!-- Google Font/Gloria Abel  -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Abel&display=swap" rel="stylesheet">

<!-- Google MATERIAL ICONS  -->
    <link href="https://fonts.googleapis.com/css2?family=Material+Icons" rel="stylesheet">

<!-- Naver Font/나눔스퀘어라운드  -->
    <style>
        @font-face{
            font-family: 'NanumSquareRoundB';
            src: local('NanumSquareRoundB'),
            url("{% static 'fonts/NanumSquareRoundOTFB.otf' %}") format("opentype");
        }
        @font-face{
            font-family: 'NanumSquareRoundEB';
            src: local('NanumSquareRoundEB'),
            url("{% static 'fonts/NanumSquareRoundOTFEB.otf' %}") format("opentype");
        }
        @font-face{
            font-family: 'NanumSquareRoundL';
            src: local('NanumSquareRoundL'),
            url("{% static 'fonts/NanumSquareRoundOTFL.otf' %}") format("opentype");
        }
        @font-face{
            font-family: 'NanumSquareRoundR';
            src: local('NanumSquareRoundR'),
            url("{% static 'fonts/NanumSquareRoundOTFR.otf' %}") format("opentype");
        }
    </style>
<!-- DEFAULT CSS LINK-->
    <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">
</head>

templates/header.html
<div class="eliot_header_logo">
    <div>
        <h1>
            <a href="{% url 'articleapp:list' %}">Eliot Works</a>
        </h1>
    </div>
    <div class="pinterest_header_navbar">
        <a href="{% url 'articleapp:list' %}" class="pinterest_header_nav">
            <span>게시글</span>
        </a>
        <a href="{% url 'projectapp:list' %}" class="pinterest_header_nav">
            <span>프로젝트</span>
        </a>
        <a href="{% url 'subscribeapp:list' %}" class="pinterest_header_nav">
            <span>구독</span>
        </a>
        {% if not user.is_authenticated %}
        <a href="{% url 'accountapp:login' %}?next={{ request.path }}" class="pinterest_header_nav">
            <span>로그인</span>
        </a>
        <a href="{% url 'accountapp:create' %}" class="pinterest_header_nav">
            <span>회원가입</span>
        </a>
        {% else %}
        <a href="{% url 'accountapp:detail' pk=user.pk %}" class="pinterest_header_nav">
            <span>설정</span>
        </a>

        <a href="{% url 'accountapp:logout' %}?next={{ request.path }}">
            <span>로그아웃</span>
        </a>
        {% endif %}
    </div>
</div>